#############################################################################
# Makefile for building: SunCloud
# Generated by qmake (2.01a) (Qt 4.8.2) on: lun. 26. janv. 12:23:46 2015
# Project:  SunCloud.pro
# Template: subdirs
# Command: c:\Qt\4.8.2\bin\qmake.exe -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile SunCloud.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.8.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src \
		sub-app \
		sub-tests

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
app\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-app-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-app: app\$(MAKEFILE) sub-src FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE)
sub-app-make_default-ordered: app\$(MAKEFILE) sub-src-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_default: app\$(MAKEFILE) sub-src-make_default FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_first-ordered: app\$(MAKEFILE) sub-src-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-make_first: app\$(MAKEFILE) sub-src-make_first FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-all-ordered: app\$(MAKEFILE) sub-src-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-all: app\$(MAKEFILE) sub-src-all FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-clean-ordered: app\$(MAKEFILE) sub-src-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-clean: app\$(MAKEFILE) sub-src-clean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-distclean-ordered: app\$(MAKEFILE) sub-src-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-distclean: app\$(MAKEFILE) sub-src-distclean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-install_subtargets-ordered: app\$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-install_subtargets: app\$(MAKEFILE) sub-src-install_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-uninstall_subtargets-ordered: app\$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-app-uninstall_subtargets: app\$(MAKEFILE) sub-src-uninstall_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall
tests\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tests\ $(MKDIR) tests\ 
	cd tests\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-tests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tests\ $(MKDIR) tests\ 
	cd tests\ && $(QMAKE) c:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o $(MAKEFILE)
sub-tests: tests\$(MAKEFILE) sub-src FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE)
sub-tests-make_default-ordered: tests\$(MAKEFILE) sub-app-make_default-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_default: tests\$(MAKEFILE) sub-src-make_default FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_first-ordered: tests\$(MAKEFILE) sub-app-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) first
sub-tests-make_first: tests\$(MAKEFILE) sub-src-make_first FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) first
sub-tests-all-ordered: tests\$(MAKEFILE) sub-app-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) all
sub-tests-all: tests\$(MAKEFILE) sub-src-all FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) all
sub-tests-clean-ordered: tests\$(MAKEFILE) sub-app-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-clean: tests\$(MAKEFILE) sub-src-clean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-distclean-ordered: tests\$(MAKEFILE) sub-app-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-distclean: tests\$(MAKEFILE) sub-src-distclean FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-install_subtargets-ordered: tests\$(MAKEFILE) sub-app-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) install
sub-tests-install_subtargets: tests\$(MAKEFILE) sub-src-install_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) install
sub-tests-uninstall_subtargets-ordered: tests\$(MAKEFILE) sub-app-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-tests-uninstall_subtargets: tests\$(MAKEFILE) sub-src-uninstall_subtargets FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SunCloud.pro  c:\Qt\4.8.2\mkspecs\win32-msvc2010\qmake.conf c:\Qt\4.8.2\mkspecs\qconfig.pri \
		c:\Qt\4.8.2\mkspecs\modules\qt_webkit_version.pri \
		c:\Qt\4.8.2\mkspecs\features\qt_functions.prf \
		c:\Qt\4.8.2\mkspecs\features\qt_config.prf \
		c:\Qt\4.8.2\mkspecs\features\exclusive_builds.prf \
		c:\Qt\4.8.2\mkspecs\features\default_pre.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\default_pre.prf \
		c:\Qt\4.8.2\mkspecs\features\debug.prf \
		c:\Qt\4.8.2\mkspecs\features\debug_and_release.prf \
		c:\Qt\4.8.2\mkspecs\features\default_post.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\default_post.prf \
		c:\Qt\4.8.2\mkspecs\features\declarative_debug.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\rtti.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\exceptions.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\stl.prf \
		c:\Qt\4.8.2\mkspecs\features\shared.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\embed_manifest_exe.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\embed_manifest_dll.prf \
		c:\Qt\4.8.2\mkspecs\features\warn_on.prf \
		c:\Qt\4.8.2\mkspecs\features\qt.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\thread.prf \
		c:\Qt\4.8.2\mkspecs\features\moc.prf \
		c:\Qt\4.8.2\mkspecs\features\win32\windows.prf \
		c:\Qt\4.8.2\mkspecs\features\resources.prf \
		c:\Qt\4.8.2\mkspecs\features\uic.prf \
		c:\Qt\4.8.2\mkspecs\features\yacc.prf \
		c:\Qt\4.8.2\mkspecs\features\lex.prf \
		c:\Qt\4.8.2\mkspecs\features\include_source_dir.prf
	$(QMAKE) -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile SunCloud.pro
c:\Qt\4.8.2\mkspecs\qconfig.pri:
c:\Qt\4.8.2\mkspecs\modules\qt_webkit_version.pri:
c:\Qt\4.8.2\mkspecs\features\qt_functions.prf:
c:\Qt\4.8.2\mkspecs\features\qt_config.prf:
c:\Qt\4.8.2\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.8.2\mkspecs\features\default_pre.prf:
c:\Qt\4.8.2\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.8.2\mkspecs\features\debug.prf:
c:\Qt\4.8.2\mkspecs\features\debug_and_release.prf:
c:\Qt\4.8.2\mkspecs\features\default_post.prf:
c:\Qt\4.8.2\mkspecs\features\win32\default_post.prf:
c:\Qt\4.8.2\mkspecs\features\declarative_debug.prf:
c:\Qt\4.8.2\mkspecs\features\win32\rtti.prf:
c:\Qt\4.8.2\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.8.2\mkspecs\features\win32\stl.prf:
c:\Qt\4.8.2\mkspecs\features\shared.prf:
c:\Qt\4.8.2\mkspecs\features\win32\embed_manifest_exe.prf:
c:\Qt\4.8.2\mkspecs\features\win32\embed_manifest_dll.prf:
c:\Qt\4.8.2\mkspecs\features\warn_on.prf:
c:\Qt\4.8.2\mkspecs\features\qt.prf:
c:\Qt\4.8.2\mkspecs\features\win32\thread.prf:
c:\Qt\4.8.2\mkspecs\features\moc.prf:
c:\Qt\4.8.2\mkspecs\features\win32\windows.prf:
c:\Qt\4.8.2\mkspecs\features\resources.prf:
c:\Qt\4.8.2\mkspecs\features\uic.prf:
c:\Qt\4.8.2\mkspecs\features\yacc.prf:
c:\Qt\4.8.2\mkspecs\features\lex.prf:
c:\Qt\4.8.2\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec c:\Qt\4.8.2\mkspecs\win32-msvc2010 CONFIG+=declarative_debug -o Makefile SunCloud.pro

qmake_all: sub-src-qmake_all sub-app-qmake_all sub-tests-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-app-make_default-ordered sub-tests-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-app-make_first-ordered sub-tests-make_first-ordered FORCE
all: sub-src-all-ordered sub-app-all-ordered sub-tests-all-ordered FORCE
clean: sub-src-clean-ordered sub-app-clean-ordered sub-tests-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-app-distclean-ordered sub-tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-app-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

sub-src-sub_Debug_ordered: src\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) debug
sub-app-sub_Debug_ordered: app\$(MAKEFILE) sub-src-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) debug
sub-tests-sub_Debug_ordered: tests\$(MAKEFILE) sub-app-sub_Debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-src-sub_Debug_ordered sub-app-sub_Debug_ordered sub-tests-sub_Debug_ordered

sub-src-sub_Release_ordered: src\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) release
sub-app-sub_Release_ordered: app\$(MAKEFILE) sub-src-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) release
sub-tests-sub_Release_ordered: tests\$(MAKEFILE) sub-app-sub_Release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) release
release: sub-src-sub_Release_ordered sub-app-sub_Release_ordered sub-tests-sub_Release_ordered

sub-src-check_ordered: src\$(MAKEFILE)
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f $(MAKEFILE) check
sub-app-check_ordered: app\$(MAKEFILE) sub-src-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f $(MAKEFILE) check
sub-tests-check_ordered: tests\$(MAKEFILE) sub-app-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-check_ordered sub-app-check_ordered sub-tests-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

