#############################################################################
# Makefile for building: SunCloud
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  SunCloud.pro
# Template: subdirs
# Command: C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\bin\qmake.exe -spec win32-msvc2013 CONFIG+=debug -o Makefile SunCloud.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub-app \
		sub-tests


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-src-qmake_all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	cd app\ && $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && $(MAKE) -f Makefile qmake_all
sub-app: sub-src FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: sub-src-make_first-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-app-make_first: sub-src-make_first FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-app-all-ordered: sub-src-all-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-app-all: sub-src-all FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: sub-src-clean-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-clean: sub-src-clean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: sub-src-distclean-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-distclean: sub-src-distclean FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: sub-src-install_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-app-qmake_all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && $(MAKE) -f Makefile qmake_all
sub-tests: sub-src FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-tests-make_first-ordered: sub-app-make_first-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-make_first: sub-src-make_first FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-all-ordered: sub-app-all-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-all: sub-src-all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-clean-ordered: sub-app-clean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-clean: sub-src-clean FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-distclean-ordered: sub-app-distclean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-distclean: sub-src-distclean FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets-ordered: sub-app-install_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-install_subtargets: sub-src-install_subtargets FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets-ordered: sub-app-uninstall_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: SunCloud.pro C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\common\shell-win32.conf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\qconfig.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\spec_post.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\lex.prf \
		SunCloud.pro
	$(QMAKE) -spec win32-msvc2013 CONFIG+=debug -o Makefile SunCloud.pro
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\common\shell-win32.conf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\qconfig.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\default_post.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\yacc.prf:
C:\Qt\Qt5.4.0_x64\5.4\msvc2013_64\mkspecs\features\lex.prf:
SunCloud.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 CONFIG+=debug -o Makefile SunCloud.pro

qmake_all: sub-src-qmake_all sub-app-qmake_all sub-tests-qmake_all FORCE

make_first: sub-src-make_first-ordered sub-app-make_first-ordered sub-tests-make_first-ordered FORCE
all: sub-src-all-ordered sub-app-all-ordered sub-tests-all-ordered FORCE
clean: sub-src-clean-ordered sub-app-clean-ordered sub-tests-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-app-distclean-ordered sub-tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-app-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

sub-src-debug_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-app-debug_ordered: sub-src-debug_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-tests-debug_ordered: sub-app-debug_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug_ordered sub-app-debug_ordered sub-tests-debug_ordered

sub-src-release_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-app-release_ordered: sub-src-release_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-tests-release_ordered: sub-app-release_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release_ordered sub-app-release_ordered sub-tests-release_ordered

sub-src-check_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\src\src.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-app-check_ordered: sub-src-check_ordered 
	@if not exist app\ mkdir app\ & if not exist app\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd app\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\app\app.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-tests-check_ordered: sub-app-check_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd tests\ && ( if not exist Makefile $(QMAKE) C:\Users\Sun-Cloud\Documents\Workspace_Qt\SunCloud\tests\tests.pro -spec win32-msvc2013 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered sub-app-check_ordered sub-tests-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

