######################################################################
# Automatically generated by qmake (2.01a) ven. 23. janv. 17:28:32 2015
######################################################################

#CONFIG += qtestlib

#QT += testlib

#CONFIG += testcase
#TEMPLATE = app
#TARGET =
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
#SOURCES +=

include(../defaults.pri)

QT += widgets

TEMPLATE = app

CONFIG   += console
CONFIG   -= app_bundle
CONFIG   -= qt

HEADERS += MetarTest.h

SOURCES += tests_runner.cc
SOURCES += MetarTest.cc

INCLUDEPATH += C:/Users/Sun-Cloud/Documents/Workspace_Qt/ExternalLib/unittest-cpp_1_4/src
#INCLUDEPATH += $$TOP_OUT_PWD/ExternalLib/unittest-cpp_1_4/src
#INCLUDEPATH += ../ExternalLib/unittest-cpp_1_4/src

LIBS += -LC:/Users/Sun-Cloud/Documents/Workspace_Qt/ExternalLib/unittest-cpp_1_4/x64/Debug -lUnitTest++.vsnet2005.debug

LIBS += -L$$TOP_PWD/lib -llibsuncloud
LIBS += C:/Users/Sun-Cloud/Documents/Workspace_Qt/ExternalLib/mdsplib/lib/libmdsp.lib
#LIBS += -L../../ExternalLib/mdsplib/lib -llibmdsp
