######################################################################
# Automatically generated by qmake (2.01a) ven. 23. janv. 17:28:32 2015
######################################################################

#CONFIG += qtestlib

#QT += testlib

#CONFIG += testcase
#TEMPLATE = app
#TARGET =
#DEPENDPATH += .
#INCLUDEPATH += .

# Input
#SOURCES +=

include(../defaults.pri)
TEMPLATE = app

CONFIG   += console
CONFIG   -= app_bundle
CONFIG   -= qt

HEADERS += MetarTest.h

SOURCES += tests_runner.cc
SOURCES += MetarTest.cc

INCLUDEPATH += ../../ExternalLib/unittest-cpp_1_4/src
LIBS += -L../../ExternalLib/unittest-cpp_1_4/lib -lUnitTest++.vsnet2005.debug
LIBS += -L../lib -llibsuncloud
LIBS += "../../ExternalLib/mdsplib/lib/libmdsp.lib"
#LIBS += "-L../../ExternalLib/mdsplib/lib -llibmdsp"
